### ISSUE TITLE
Unable to Resolve Folder Path - Not working

### ISSUE THREAD

**Issue by waleedahmed3045** [erikdesjardins/contents-loader#3]
I have following directory structure and I am seeing the following error 
![image](https://user-images.githubusercontent.com/5687191/37568799-9f2eeff0-2ab0-11e8-8c78-9251901c0086.png)

![image](https://user-images.githubusercontent.com/5687191/37568795-956d20e0-2ab0-11e8-95c5-6d0c8809db50.png)

Also the travis ci build for this repository also failed

**Comment by erikdesjardins** [comment]
I'm pretty sure that this loader can't work in general, without a plugin or some terrible `this._compilation` hacks. Though it's been so long that I don't remember exactly why.

You should use [`require.context`](https://webpack.js.org/guides/dependency-management/#require-context) instead.
